version: "3"
services:

  db:
    container_name: wiki_db
    image: postgres:11-alpine
    environment:
      POSTGRES_DB: wiki
      POSTGRES_PASSWORD: wikijsrocks
      POSTGRES_USER: wikijs
      TZ: Asia/Shanghai
    logging:
      driver: "none"
    restart: unless-stopped
    volumes:
      - db-data:/var/lib/postgresql/data

  wiki:
    container_name: wiki_web
    image: requarks/wiki:2
    depends_on:
      - db
    environment:
      DB_TYPE: postgres
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: wikijs
      DB_PASS: wikijsrocks
      DB_NAME: wiki
      TZ: Asia/Shanghai
    restart: unless-stopped
    volumes:
      - /home/wiki/assets/favicons:/wiki/assets/favicons
    ports:
      - "3000:3000"

volumes:
  db-data: